import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  await knex('product_catalog').del();
  await knex('shipping_option').del();
  await knex('credit_source').del();

  await knex('product_catalog').insert([
    {
      id: 'pc_001',
      name: 'Wireless Mouse',
      description: 'Ergonomic Bluetooth mouse',
      price: 19.99,
      currency_code: 'eur',
      thumbnail: 'https://picsum.photos/seed/mouse/200',
      in_stock: true,
      product_id: 'prod_01',
      variant_id: 'var_01',
      product_title: 'Wireless Mouse',
      variant_title: 'Black',
      variant_sku: 'SKU-001',
      unit_price: 19.99,
    },
    {
      id: 'pc_002',
      name: 'USB Cable',
      description: 'Braided 1m USB-C cable',
      price: 9.99,
      currency_code: 'eur',
      thumbnail: 'https://picsum.photos/seed/cable/200',
      in_stock: true,
      product_id: 'prod_02',
      variant_id: 'var_02',
      product_title: 'USB Cable',
      variant_title: '1m',
      variant_sku: 'SKU-002',
      unit_price: 9.99,
    },
    {
      id: 'pc_003',
      name: 'Laptop Stand',
      description: 'Aluminum adjustable stand',
      price: 49.99,
      currency_code: 'eur',
      thumbnail: 'https://picsum.photos/seed/stand/200',
      in_stock: true,
      product_id: 'prod_03',
      variant_id: 'var_03',
      product_title: 'Laptop Stand',
      variant_title: 'Silver',
      variant_sku: 'SKU-003',
      unit_price: 49.99,
    },
    {
      id: 'pc_004',
      name: 'Mechanical Keyboard',
      description: 'Tactile switches, hot-swappable',
      price: 129.0,
      currency_code: 'eur',
      thumbnail: 'https://picsum.photos/seed/keyboard/200',
      in_stock: true,
      product_id: 'prod_04',
      variant_id: 'var_04',
      product_title: 'Mechanical Keyboard',
      variant_title: 'Brown',
      variant_sku: 'SKU-004',
      unit_price: 129.0,
    },
    {
      id: 'pc_005',
      name: 'Webcam HD',
      description: '1080p with privacy shutter',
      price: 79.5,
      currency_code: 'eur',
      thumbnail: 'https://picsum.photos/seed/webcam/200',
      in_stock: false,
      product_id: 'prod_05',
      variant_id: 'var_05',
      product_title: 'Webcam HD',
      variant_title: 'Black',
      variant_sku: 'SKU-005',
      unit_price: 79.5,
    },
  ]);

  await knex('shipping_option').insert([
    {
      id: 'so_std',
      name: 'Standard',
      amount: 5.0,
      currency_code: 'eur',
      provider_name: 'PostEU',
      estimated_delivery: '3-5 days',
      region_id: 'reg_eu',
    },
    {
      id: 'so_exp',
      name: 'Express',
      amount: 15.0,
      currency_code: 'eur',
      provider_name: 'DHL',
      estimated_delivery: '1-2 days',
      region_id: 'reg_eu',
    },
    {
      id: 'so_ovn',
      name: 'Overnight',
      amount: 25.0,
      currency_code: 'eur',
      provider_name: 'UPS',
      estimated_delivery: 'Next day',
      region_id: 'reg_eu',
    },
  ]);

  await knex('credit_source').insert([
    {
      id: 'cs_ref_01',
      reference: 'refund',
      reference_id: 'ref_01',
      amount: 10.0,
      currency_code: 'eur',
      customer_id: 'cus_001',
      description: 'Refund for prior order',
    },
    {
      id: 'cs_gc_01',
      reference: 'gift_card',
      reference_id: 'gc_01',
      amount: 25.0,
      currency_code: 'eur',
      customer_id: 'cus_001',
      description: 'Birthday gift card',
    },
    {
      id: 'cs_sc_01',
      reference: 'store_credit',
      reference_id: 'sc_01',
      amount: 5.5,
      currency_code: 'eur',
      customer_id: 'cus_002',
      description: 'Goodwill credit',
    },
  ]);
}
